### ISSUE TITLE
please help me to solove this problem, this vue project is alone to use a ip and port(3000), want to inside the screen sharing to this vue project, but the RTCMultiConnection is only to occupy this ip and port(9001),how to handle this issue?

### ISSUE THREAD

**Issue by frankrenping** [muaz-khan/RTCMultiConnection#1066]

**Comment by frankrenping** [comment]
my vue project don't together use the same IP and different port with RTCMultiConnection project? but i already to use another chat server in this vue projcet, and normal work, and run programe at current have below error:
Uncaught TypeError: navigator.getUserMedia is not a function
at getUserMediaHandler (RTCMultiConnection.js:3525:27)
at RTCMultiConnection.connection.invokeGetUserMedia (RTCMultiConnection.js:5127:13)
at RTCMultiConnection.connection.getUserMedia.connection.captureUserMedia (RTCMultiConnection.js:4634:36)
at RTCMultiConnection.js:4290:28
.....
