### ISSUE TITLE
SyntaxError: Use of const in strict mode.

### ISSUE THREAD

**Issue by CT-Thompson** [muaz-khan/RTCMultiConnection#406]
Hello, 

I've been using this project for a little over a year. Everything was working fine.

Today I upgraded. I followed the installation guide and installed into a new directory (preserving the old, working one). When I try to start server.js I get:

/RTC/node_modules/socket.io/node_modules/socket.io-client/node_modules/engine.io-client/node_modules/ws/index.js:9
const WebSocket = require('./lib/WebSocket');
^^^^^
SyntaxError: Use of const in strict mode.
    at Module._compile (module.js:439:25)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)
    at Module.require (module.js:364:17)
    at require (module.js:380:17)
    at Server.init (/RTC/node_modules/socket.io/node_modules/engine.io/lib/server.js:119:16)
    at new Server (/RTC/node_modules/socket.io/node_modules/engine.io/lib/server.js:65:8)
    at Function.attach (/RTC/node_modules/socket.io/node_modules/engine.io/lib/engine.io.js:123:16)
    at /RTC/node_modules/socket.io/lib/index.js:258:23

Does this have to do with my node version?

node --version
v0.10.48

Thanks,

CT

**Comment by muaz-khan** [comment]
Please try older socket.io:

```sh
# remove current socket.io
npm uninstall socket.io

# install specific version
npm install socket.io@0.9.x
```

**Comment by CT-Thompson** [comment]
Yes, that did it. 

Thank you.
