### ISSUE TITLE
RTCMultiConnection Installation Problem iisnode encountered

### ISSUE THREAD

**Issue by samehdoush** [muaz-khan/RTCMultiConnection#739]
Hello Mr. Khan,

I have installed RTCMultiConnection and run server.js file in listen to 
http://nodeserv.eritqaa.com/ 
```

iisnode encountered an error when processing the request.

HRESULT: 0x2
HTTP status: 500
HTTP reason: Internal Server Error
You are receiving this HTTP 200 response because system.webServer/iisnode/@devErrorsEnabled configuration setting is 'true'.

In addition to the log of stdout and stderr of the node.exe process, consider using debugging and ETW traces to further diagnose the problem.

The last 64k of the output generated by the node.exe process to stderr is shown below:

Application has thrown an uncaught exception and is terminated:
SyntaxError: Use of const in strict mode.
    at Module._compile (module.js:439:25)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)
    at Module.require (module.js:364:17)
    at require (module.js:380:17)
    at Object.<anonymous> (h:\root\home\eritqaaacademy-001\www\site8testnode\server.js:9:18)
    at Module._compile (module.js:456:26)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)
```

**Comment by muaz-khan** [comment]
Did you clone https://github.com/muaz-khan/RTCMultiConnection and deploy it as it is? Without any modification?

I'm using same code here: https://rtcmulticonnection.herokuapp.com/demos/

Config variables (though NOT required):
![heroku config vars](https://user-images.githubusercontent.com/477092/54276262-b718e980-45ae-11e9-9966-6412220ebae5.png)

**Comment by samehdoush** [comment]
Thank you for replying, I did not reproduce it as I did some modifications and I was on the canvas but for the server it is as I will try as it is in the picture

**Comment by samehdoush** [comment]
File server as it is and spoke to the hosting company and responded to the following way:

We are Hosting node.js applications in IIS on Windows via IISNode, so you need to update listening port to use "process.env.PORT" in your code.So you can not custom your port with our server, would you please update the js to listen that port.

Thank you.

**Comment by muaz-khan** [comment]
* https://github.com/muaz-khan/RTCMultiConnection/blob/master/server.js#L269

Already using `process.env.PORT` here:

```javascript
httpApp = httpApp.listen(process.env.PORT || PORT, process.env.IP || "0.0.0.0", function() {
    RTCMultiConnectionServer.afterHttpListen(httpApp, config);
});
```

To split in lines:

```javascript
httpApp = httpApp.listen(
        process.env.PORT || PORT, 
        process.env.IP || "0.0.0.0", 
        function() {
                RTCMultiConnectionServer.afterHttpListen(httpApp, config);
       }
);
```

**Comment by samehdoush** [comment]
Thank you It seems that the problem in the hosting company is there is a hosting company supports the node to build the server
