### ISSUE TITLE
Just tried and got error

### ISSUE THREAD

**Issue by JerryGeis** [muaz-khan/RTCMultiConnection#855]
I just followed the steps for  "Install on your own website".
I get this error ????
What to do?

node server --port=9001
/var/www/html/demo/node_modules/ws/lib/websocket.js:347
      ...options
      ^^^

SyntaxError: Unexpected token ...
    at createScript (vm.js:56:10)
    at Object.runInThisContext (vm.js:97:10)
    at Module._compile (module.js:549:28)
    at Object.Module._extensions..js (module.js:586:10)
    at Module.load (module.js:494:32)
    at tryModuleLoad (module.js:453:12)
    at Function.Module._load (module.js:445:3)
    at Module.require (module.js:504:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (/var/www/html/demo/node_modules/ws/index.js:3:19)

My demo directory: (everything seems installed)
admin  bower.json  config.json  CONTRIBUTING.md  demos  dev  dist  docs  fake-keys  favicon.ico  Gruntfile.js  LICENSE.md  logs.json  node_modules  npm-test.js  package.json  README.md  server.js

**Comment by JerryGeis** [comment]
Ok - So my CentOS node.js is older version 6. So I removed that and installed version 12.
This command now runs. Great I thought.

I then browser with chrome to the IP:9001 and I see the demo page - Great I thought.
I scroll down to scalable audio/video broadcast click it. click Open or join and ERROR

navigator.getUserMedia is not a function RTCMultiConnection.min.js:16 

What do I do with that???

Jerry

**Comment by JerryGeis** [comment]
Seems you "have" to use https to get past this issue of getUserMedia...   So now I'm running "node server --ssl" and I get the first users video.   However when I join from the same PC or another PC I get the "Number of broadcast viewers" to increment - but no audio or video is shown.
F12 console shows:

isRoomJoined  true
room-xyz online
room-xyz-offline

So close... Any suggestions.

Jerry

**Comment by Patrick-Vogt** [comment]
Why don't you try to use a real domain with a real ssl cert from lets encrypt  and configure your webbrowser nginx) to proxy the requests. That means you can use it without the port. 

I will never understand why people make themself a hard time with localhost/ip things instead of testing in real life scenarios...
